### ISSUE TITLE
export list of addresses for account

### ISSUE THREAD

**Issue by jangorecki** [blockchain/My-Wallet-V3-Frontend#121]
Feature request.
Would be nice to have easy way to export addresses for account without enabling api or revealing private keys. See [this stackexchange](http://bitcoin.stackexchange.com/questions/40582/export-a-list-of-addresses-associated-to-blockchain-info-account/40588#comment46683_40588).

Simply button for popup with `addr1\naddr2\naddr3` to copy-paste it would be well enough.

**Comment by Sjors** [comment]
Thanks. The latest version allows you to export the account xpub (settings -> my accounts -> reveal xpub). You can then generate all addresses e.g. using BitcoinJS in a NodeJS console. What do you need this for?

**Comment by jangorecki** [comment]
I don't have *my accounts* in settings, I do have only *account settings* but I don't see *xpub* anywhere. Was it rolled out to production? or maybe it is a merchant only feature?
External software like BitcoinJS or NodeJS doesn't really answer that simple need.
I use it to paste list of my addresses into R script. R is statistical software. The R script will consume the list by fetching addresses unspents in time intervals. So basic addresses string delimited with `\n` or even a comma `,` is well enough to process them.

**Comment by Sjors** [comment]
Are you sure you're talking about the new (alpha) wallet on https://alpha.blockchain.info? That's what this repository is about. For the original wallet at https://blockchain.info/, please see [this](https://github.com/blockchain/My-Wallet) repository. 

In the original wallet you can export your wallet as a JSON file which contains a dictionary with addresses. That shouldn't be too hard to process with R, but be careful where you run it, since it contains private keys too. 

Alternatively go to My Transactions, click the dropdown next to show, click export history and pick any format. If you open a developer console in your browser you'll see that a request is made to `https://blockchain.info/export-history?active=16Ha...|1abc...|.....` which is a list of all your addresses. You don't need the resulting CSV file, just the URL where it gets it from.

 [Support](https://blockchain.zendesk.com/home) might know some other tricks.

**Comment by jangorecki** [comment]
OK, that's explain a lot... just came from there [My-Wallet#125](https://github.com/blockchain/My-Wallet/issues/125)
