### ISSUE TITLE
Angular.ui native international-phone-number / intl-tel-input alternative

### ISSUE THREAD

**Issue by Sjors** [blockchain/My-Wallet-V3-Frontend#152]
We're trying to remove jQuery as a dependency. The phone number entry field powered by [international-phone-number](https://github.com/mareczek/international-phone-number/). This is a wrapper around the [intl-tel-input](https://github.com/Bluefieldscom/intl-tel-input) jQuery plugin.

Here's where I use it:
https://github.com/blockchain/My-Wallet-V3-Frontend/blob/master/app/templates/configure-mobile-number.jade#L3-L11 

<img width="261" alt="screenshot" src="https://cloud.githubusercontent.com/assets/10217/10225496/fa164dd6-6817-11e5-80b6-50ee761afe7d.png">

Two approaches have been tried so far:
1 - replace all jQuery methods with more primitive Javascript code;
2 - replace jQuery with a smaller framework, e.g. [Zepto](http://zeptojs.com)

I would prefer a solution more or less built from scratch on top of either [ui.bootstrap.typeahead](https://angular-ui.github.io/bootstrap/#/typeahead) or [ui.select](https://github.com/angular-ui/ui-select).

The country flags can be found here: https://github.com/behdad/region-flags

Rather than forking intl-tel-input and international-phone-number, I would suggest creating two new projects:

1 - a purely functional JS library. It takes a user input string and
returns a formatted phone numer and country code. Some of the code you'll need:

https://github.com/Bluefieldscom/intl-tel-input/blob/master/src/js/data.js
https://github.com/Bluefieldscom/intl-tel-input/blob/master/lib/libphonenumber/src/utils.js

For example the function would convert the input `"1650"` to `{number: "+1 (650)", country: "us", valid: false}`. 

2 - an AngularJS wrapper that uses (1) and ui.select or ui.bootstrap, to
create a UI similar to international-phone-number / intl-tel-input. It can have fewer features and configuration options.

The end result would e.g. be a directive used like this:
`<phone-number ng-model="theNumber"  default-country="us" preferred-countries="us gb ca" />`

If `theNumber` is already set, it should show that initial value and the correct country flag on load. As the user types it should correct the number formatting, update the country flag, update the ng-model and validate it.

Bounty:
 [![Bountysource](https://www.bountysource.com/badge/issue?issue_id= 27091686)](https://www.bountysource.com/issues/27091686-angular-ui-native-international-phone-number-intl-tel-input-alternative)

See also the discussion at mareczek/international-phone-number#44

**Comment by Ahimta** [comment]
@Sjors that makes sense.

I am a college student, taking some MOOCS and working on other projects too.
It would be helpful for me to know when you want this done (e.g: anytime, in a month, ASAP).
So that I can prioritize this project and know if I have to do a one-man hackathon if necessary :)

Note that my time zone is GMT+3 all year. So most days I will be asleep by now (10 P.M)

**Comment by Sjors** [comment]
From our point of view the sooner the better (e.g. within a few weeks), but I prefer it if you take your time and do it well and not rush it. Keep us posted on updates. You should also keep an eye on the Bountysource page in case someone else starts working on it.

**Comment by Ahimta** [comment]
Hi @Sjors, I just finished up with the initial prototype.
You can find it here: https://github.com/Ahimta/phone-number
And you can try it on a demo page here: http://ahimta.github.io/phone-number/

Looking forward to your feedback.

**Comment by Sjors** [comment]
@Ahimta that's a great start! A couple of suggestions:
Usually in a Bower package the final (minified) javascript is in `/dist`.  See more tips here: http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/

Can you explain what src/js/trie.js is trying to achieve?

About /src/js/libphonenumber.js: how is it different from googlei18n/libphonenumber? If it's the same, can you include it as a git submodule instead? Maybe you can ask them to publish it on Bower? If it's different, I still think it should be in a separate repository; that makes it easier for non angular projects to reuse it.

The original project uses util.js; do you know what that is for? If it's useful, can you include it? (again, as submodule / bower dependency)

**Comment by Sjors** [comment]
To be more precise: I think https://github.com/Ahimta/phone-number/blob/master/src/js/phone-number.js#L10-L82 should be it's own repository (because it's not AngularJS specific). That repository can include libphonenumber.js either directly or via another Bower dependency / submodule. If that makes sense...

**Comment by Ahimta** [comment]
I am very aware of the many issues in the code right now.
I thought it would be better to present a usable solution to get more feedback,
than present a full solution (e.g: published in bower and npm),
which would take more time and be harder to change (undesirable in early development).

Ideally:
1. There should be dist/phone-number.{min.js,js} files.
2. The project should be usable through package managers (e.g: bower, npm, component).
3. The majority of the code should reside in different repos (e.g: Trie.js, countries.js).
4. Use some tools to ensure code quality (e.g: jshint).
5. Limit the use of global variables (if ever used).
6. Inline templates (especially in dist/*.js) instead of using `templateUrl`.
7. Consider using browsify.
8. Write more meaningful tests.
9. Add some property-based testing to catch more hard-to-predict bugs.
10. Make more use of Angular (e.g: $parsers, $formatters).

I will do most of these eventually (before you start using it in your own project).
And of course, if you're satisfied with the current functionality I will start working on them right away.

However, I did some stuff initially that I thought would make it easier to get me started:
1. Use bower and gulp. I started using index.html and CDNs and it got messy from the start.
2. Putting all the files in the root folder started making it hard to navigate the code so I moved them into folders.
3. I automated deploying to GitHub Pages to make it easier to try; doing manually takes about the same time.
4. I integrated the project to Travis to make sure it works anywhere (not just on my computer or Node v4.1).
5. I made some changes to Grunt tasks so that src/ contains only source files; it always took me extra time to get to a source file to edit it.
6. Use pure functions as much as possible and minimize state; it's easier to reason about functions that produce the same output for a given input, than functions that use global scope or the directives scope.
7. Add Trie.js for fast prefix operations. The brute force is too slow that it could take minutes just to build the data structure. And I have a good understanding of data structures, so it was easier for me to write my own data structure, and it simplifies many parts of the code.

utils.js is the same as lib/js/libphonenumber.min.js.
I couldn't fine any maintained libphonenumber package in both bower and npm.
Worse still the official repo doesn't even have a consumable javascript file.
To use it you have to compile using ant, which what int-tel-input has done, so I just copied it from there.
lib/js/libphonenumber.js is only for documentation sake. Only lib/js/libphonenumber.min.js is usable.

src/js/trie.js is a [TRIE](https://en.wikipedia.org/wiki/Trie).
It provides fast prefix operations, which simplifies many parts of the code.
The other approaches are either very slow (minutes just to load the data),
or somewhat hacky, which would take even more time to implement (for me at least).

Sorry, for the long comment :-)

**Comment by Sjors** [comment]
Great plan. I like incremental changes. Once you've done 1,2 (bower) and 3 from the first list, I'll create a branch on our end where we can experiment with it.

**Comment by Sjors** [comment]
By the way, we moved the bounty to this Github issue:  
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id= 27091686)](https://www.bountysource.com/issues/27091686-angular-ui-native-international-phone-number-intl-tel-input-alternative)

**Comment by Ahimta** [comment]
Hi @Sjors, you can now install it directly using npm or bower.

```bash
bower install --save bc-phone-number
npm install --save bc-phone-number
```
```js
angular.module('myWallet', ['bcPhoneNumber']);
```

[bc-phone-number](https://github.com/Ahimta/bc-phone-number) only contains the code related to Angular.

You can find the rest in:
1. [bc-css-flags](https://github.com/Ahimta/bc-css-flags)
2. [bc-countries](https://github.com/Ahimta/bc-countries)
3. [digits-trie](https://github.com/Ahimta/digits-trie)

They are all also available in bower and npm.
I tried my best to divide the project into different repos.
It's still not perfect, but it will be better hopefully.

In addition, bc-phone-number should work fine with Content-Security-Policy.

One major issue that's still standing, is that sometimes the text cursor moves to the end when the formatted number is being edited in the beginning or end.
One possible solution is to use either ng-change or native change input event.
This could take some time, but still very fixable :)

**Comment by Sjors** [comment]
This is great progress! I'll leave some issues on Github as feedback.

Can you make a Bower release with the dist folder in it that you created yesterday? https://github.com/Ahimta/bc-phone-number/tree/master/dist/js

You should probably slow down with the version numbers, see e.g. http://semver.org 
I would start with version 0.1.0 and when it's more stable call it 1.0.0.

For convenience it would be nice to have a single dist js / css / images that contains all the dependencies, but for security review it's easier if they are kept separate like now.

**Comment by Sjors** [comment]
@Ahimta: you did a great job on this, please claim your bounty!

**Comment by Ahimta** [comment]
@Sjors thanks, it has been a pleasure working with you.
